version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: simba_api_app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database_services
      - DB_PORT=5432
      - DB_USER=simba_dev
      - DB_PASSWORD=simba_2025
      - DB_NAME=simba_dev
    volumes:
      - .:/app
    networks:
      - simba-network
    restart: always

networks:
  simba-network:
    external: true